# Generated by Django 6.1.1 on 2026-09-09 21:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cagada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio_cagada', models.DateTimeField()),
                ('hora_final_cagada', models.DateTimeField()),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('observaciones', models.TextField(blank=True)),
                ('categorizacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('color', models.CharField(max_length=7)),
                ('visible_para_otros', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cagadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
