# Generated by Django 6.1.1 on 2026-09-09 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cagadas', '0001_initial'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cagada',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cagadas', to='ubicaciones.ubicacion'),
        ),
    ]
