# Generated by Django 6.1.1 on 2026-09-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cagadas', '0002_cagada_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cagada',
            name='categorizacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Rápida'), (3, 'Larga'), (4, 'Difícil'), (5, 'Tranquila'), (6, 'Explosiva'), (7, 'Interrumpida'), (8, 'Urgente'), (9, 'Satisfactoria'), (10, 'Problemática')], default=1),
        ),
        migrations.AlterField(
            model_name='cagada',
            name='duracion',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
