# Generated by Django 6.1.1 on 2026-09-11 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cagadas', '0003_alter_cagada_categorizacion_alter_cagada_duracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('UY_PA', '💀 Uy pa'), ('DURISIMO', '🔥 Durísimo hermano'), ('GG', '🤝 GG'), ('MIERDA', '💩 Una mierda'), ('MEDIQUESE', '🤒 Medíquese')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cagada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='cagadas.cagada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'cagada'), name='una_reaccion_por_usuario_cagada')],
            },
        ),
    ]
